### ISSUE TITLE
Error not clear when eval transcripts are missing

### ISSUE THREAD

**Issue by vimalmanohar** [fgnt/pb_chime5#2]
https://github.com/fgnt/pb_chime5/blob/ff793a29037d4fb6e4b1959f3d464fb0dc8c767c/pb_chime5/database/chime5/create_json.py#L221

When eval transcripts are missing and EVAL_TRANSCRIPTIONS_MISSING is False (by default), there is no error message. However, an assertion is raised at this line.

**Comment by boeddeker** [comment]
Thanks for reporting this. The PR #3 improved the exception msg.
