### ISSUE TITLE
`make` command take too long to finish

### ISSUE THREAD

**Issue by vineelpratap** [fgnt/pb_chime5#20]
Hi, 
 I was trying to generate CHiME6 eval files using scripts from Kaldi and noticed that my script gets stuck at this stage .
 
 ```
 python -m pb_chime5.database.chime5.create_json -j cache/chime6.json -db kaldi/egs/chime6/s5_track1/CHiME6 --transcription-path kaldi/kaldi/egs/chime6/s5_track1/CHiME6/transcriptions --chime6
 ``` 
 which is called from here https://github.com/kaldi-asr/kaldi/blob/master/egs/chime6/s5b_track1/local/decode.sh#L102
 
Do you have any estimate of how long is the `make` command supposed to take. And, if there are any ways to speed up the process. 

For example, simply using more threads for make command using ` make -j80 cache/chime6.json` doesn't seem to help...

Thanks in advance !

**Comment by vineelpratap** [comment]
We realized that it is because of some wierd MPI configs in my HPC cluster. Everything works now !

**Comment by boeddeker** [comment]
Hi,

I am glad, that you found a solution.
A speedup for this function is difficult, but it should not take much time.
That function creates the metadata, that is later used.
