### ISSUE TITLE
mpi -> dlp_mpi

### ISSUE THREAD

**Issue by sw005320** [fgnt/pb_chime5#6]
This part should be `dlp_mpi` (pointed by @yubouf)
https://github.com/fgnt/pb_chime5/blob/5fe79744498f6f19ef1214877a71664cb4b55a26/pb_chime5/scripts/kaldi_run.py#L33

**Comment by boeddeker** [comment]
Thank you. I fixed it. I have to write a small test that executs also this script.

**Comment by sw005320** [comment]
Thanks a lot!
