### ISSUE TITLE
new format for CHiME-6

### ISSUE THREAD

**Issue by sw005320** [fgnt/pb_chime5#7]
hi,

Now, we're working on the CHiME-6 baseline, and try to include the GSS in the baseline recipe.
In the CHiME-6, we plan to synchronize the audio files across arrays and use the same time across them.
The audio files are modified accordingly and the JSON format will be changed as follows:
- CHiME-5
```
        "end_time": {
            "original": "0:01:00.38",
            "U01": "0:01:00.38",
            "U02": "0:01:00.39",
            "U03": "0:01:00.38",
            "U04": "0:01:00.37",
            "U05": "0:01:00.38",
            "U06": "0:01:00.36",
            "P09": "0:01:00.38",
            "P10": "0:01:00.38",
            "P11": "0:01:00.38",
            "P12": "0:01:00.38"
        },
        "start_time": {
            "original": "0:00:57.54",
            "U01": "0:00:57.54",
            "U02": "0:00:57.55",
            "U03": "0:00:57.54",
            "U04": "0:00:57.53",
            "U05": "0:00:57.54",
            "U06": "0:00:57.52",
            "P09": "0:00:57.54",
            "P10": "0:00:57.54",
            "P11": "0:00:57.54",
            "P12": "0:00:57.54"
        },
        "words": "[noise] What were we talking about again? [inaudible 0:00:58.96]",
        "speaker": "P12",
        "session_id": "S03"
```
- CHiME-6 (planning)
```
    {
        "end_time": "0:01:00.39",
        "start_time": "0:00:57.55",
        "words": "[noise] What were we talking about again? [inaudible 0:00:58.96]",
        "speaker": "P12",
        "session_id": "S03"
    },
```

Could you make an option to follow such a format?

**Comment by sw005320** [comment]
Added @jonbarker68 for this discussion.

**Comment by boeddeker** [comment]
Hi,
sure, I can add such an option.
This makes the code at many positions simpler.

**Comment by sw005320** [comment]
Many thanks!

**Comment by sw005320** [comment]
I just invited @boeddeker to our private repo. In the repo, we already have the version for the new format and test it with the beamformit etc. are working but not for GSS and want your help.

**Comment by boeddeker** [comment]
Thanks for the invitation, I got it.

I started to support your planned json style. I created a dummy json with your proposed format and adjusted the code to support it.
The `pb_chime5.database.chime5.create_json` got a `--chime6` flag and the `pb_chime5.scripts.kaldi_run` got a `chime6=True` option.

The test run worked in the chime6 mode.

I am not sure, if I find the time tomorrow to test it with your repository.
On Friday I have some more time to test it.

**Comment by sw005320** [comment]
This is very helpful.
I think I can test your PR on my side at least.

**Comment by boeddeker** [comment]
Thanks. The PR is now also merged.

Hint: The default path for our json in the CHiME5 mode changed to `cache/chime6.json` (i.e. 5 -> 6)

**Comment by sw005320** [comment]
This change is incorporated in our ongoing chime6 recipe and we confirmed that it is working.
